### PR TITLE
fix: ensuring close event is emited after stream has ended. 

### LINKED ISSUE #321: [BUG] Pipeline stream unexpectly being closed when using `extract`
# What / Why

When you attempt to extract a tarball through streams sometimes it will be closed with an error: `[ERR_STREAM_PREMATURE_CLOSE]: Premature close`, although the files are successfully extracted. No [Errors Codes](https://github.com/npm/node-tar#error-codes) are shown in the process.

It seems to happen only on newer versions of Node > v18 
Looking at [the spec](https://nodejs.org/api/stream.html#streamfinishedstream-options-callback) it seems now that streams that emit a `close` event _before_ a `end` event trigger this error, so worth taking a look on that.

## When

* n/a

## Where

* n/a

### Current Behavior

* It throws an `ERR_STREAM_PREMATURE_CLOSE` Error when trying to extract

### Steps to Reproduce

```
$ nvm install 18.7.0
$ npm install tar got
$ mkdir output
```

```js
import stream from 'node:stream';
import { promisify } from 'util';
import tar from 'tar';
import got from 'got';

const pipeline = promisify(stream.pipeline);

pipeline(
  got.stream('https://codeload.github.com/npm/node-tar/tar.gz/main'),
  tar.extract({ cwd: './output' }, ['node-tar-main/lib'])
)
```

### Expected Behavior

* It should extract the content of the archive without any issues

## References

* Related to Next.js Issue [#39321](https://github.com/vercel/next.js/issues/39321)

### PR DESCRIPTION
**Pull request by webark**
For node 18 compatibility

Fixes #321

Node 18 pipelines specifically require the end event to be emitted and handled before the close event is.

I tried a test with a local tar file and it was still passing without the fix, but a remote tar file failed, so just stuck to that.

### CODE REVIEW

File: lib/parse.js [hunk 1]
```diff
@@ -114,6 +113,9 @@ module.exports = warner(class Parser extends EE {
     this[ABORTED] = false
     this[SAW_NULL_BLOCK] = false
     this[SAW_EOF] = false
+
+    this.on('end', () => setTimeout(() => this.emit('close')))
```
Comment (webark) [inline lib/parse.js:117]: Would love something better that an empty setTimeout here. Maybe someone has some thoughts?

**Comment by webark** [comment]
@jeferson-sb @lukekarrys let me know if you have any thoughts on this.

File: lib/parse.js (hunk 1 above)
Comment (bergundy) [reply lib/parse.js:117]: You might be able to use `queueMicrotask` or `Promise.resolve().then` to avoid waiting for a next tick of the event loop.

Comment (webark) [reply lib/parse.js]: Thanks @bergundy ! `queueMicrotask` was what I was looking for, and seems to work great 👍

Comment (webark) [reply lib/parse.js]: Ahhhh.. good point 👍 ok. I'll make that change. Thanks 😊

Comment (webark) [reply lib/parse.js]: ok @bergundy switched to nextTick to support node 10.

**Comment by webark** [comment]
@lukekarrys squashed the commits and reworded to pass the commit lint.

File: lib/parse.js (hunk 1 above)
Comment (fritzy) [reply lib/parse.js]: npm already uses features that aren't supported in Node 10. We tend to drop support for Node versions as they go out of LTS.

Comment (webark) [reply lib/parse.js]: I did notice that node 10 was in the testing versions.

**Comment by webark** [comment]
@lukekarrys pinging again to see if you can approve the verifications.

File: lib/parse.js (hunk 1 above)
Comment (lukekarrys) [reply lib/parse.js]: Due to the heavy use of this package outside of `npm/cli`, I decided to keep the engines at `>=10` to avoid a major release. So it's good to use `nextTick` for now.

@webark one minor nit: would you be able to add a comment flagging that for updating when node 10 support is dropped? something like `TODO: change to queueMicrotask when node 10 support is dropped`

**Comment by lukekarrys** [comment]
Thanks for sticking with this @webark! I left a note above about a comment, but I decided I'd rather approve and merge and not risk forgetting about this (yet again).

Thanks again! This should be released as a patch within the next week.

**Comment by webark** [comment]
Thank you! :) Just saw your previous comment and was about to push a change. I'll check back in a couple of months once node 18 has baked a bit and look into opening a PR to switch it to `nextTick`

**Comment by bergundy** [comment]
nit: `Promise.resolve().then` which works on Node 10 is equivalent to `queueMicrotask` and cheaper than `nextTick`.
It's not critical, just thought I'd bring this to your attention.
Thanks everyone for putting this fix together and reviewing!

**Comment by webark** [comment]
@bergundy I didn't look into the performance case of that :( Should I open another PR with the Promise approach?

**Comment by bergundy** [comment]
It’s really not too critical imho, up to you.

**Comment by bergundy** [comment]
Here’s more information about the difference between tasks and microtasks FTR: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by webark** [comment]
That's was a good read! thanks for sharing 😊 

@lukekarrys Do you know how long that node 10 is going to be supported?

We could also leverage the promise conditionally depending on if the micro task is available if node 10 support is going to be around for longer than a couple of months.

**Comment by bergundy** [comment]
I see a release PR was created by a bot: #326, can we get this approved please?

**Comment by lukekarrys** [comment]
> I see a release PR was created by a bot: #326, can we get this approved please?

This has been released as `6.1.12`. Sorry for the delay, I wanted to do a few upstream tests in `npm/cli` first. Thanks to @webark for the fix and @bergundy for the review and help!
